[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# 添加 RPC 别名，方便使用
# Foundry 会自动加载项目根目录下的 .env，无需额外代码。
# forge script script/Counter.s.sol --rpc-url bsctestnet --broadcast --mnemonics ${MNEMONIC}

# [profile.local]
# eth-rpc-url = "${BSC_TESTNET_RPC_URL}"

# [profile.bsctestnet]
# eth-rpc-url = "${BSC_TESTNET_RPC_URL}"

[rpc_endpoints]
bsctestnet = "${BSC_TESTNET_RPC_URL}"